// Generated by CoffeeScript 1.3.1
(function() {

  define(['jquery', 'underscore', 'backbone', 'router'], function($, _, Backbone, Router) {
    return {
      initialize: function() {
        return Router.initialize();
      }
    };
  });

}).call(this);
